version: '3.8'

services:
  go-auth:
    container_name: GO_AUTH
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=${MONGOURI}
      - DB_NAME=${DBNAME}  # Replace with actual environment variables
      - PORT=${PORT}
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
